// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: enums.proto
// Protobuf Java Version: 4.30.2

package top.opendsp.proto.enums;

public final class OpenDspEnums {
  private OpenDspEnums() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 30,
      /* patch= */ 2,
      /* suffix= */ "",
      OpenDspEnums.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * opendsp枚举定义
   * </pre>
   *
   * Protobuf enum {@code top.opendsp.proto.OsType}
   */
  public enum OsType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKNOWN_OS = 0;</code>
     */
    UNKNOWN_OS(0),
    /**
     * <code>IOS = 1;</code>
     */
    IOS(1),
    /**
     * <code>ANDROID = 2;</code>
     */
    ANDROID(2),
    /**
     * <code>HARMONYOS = 3;</code>
     */
    HARMONYOS(3),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 30,
        /* patch= */ 2,
        /* suffix= */ "",
        OsType.class.getName());
    }
    /**
     * <code>UNKNOWN_OS = 0;</code>
     */
    public static final int UNKNOWN_OS_VALUE = 0;
    /**
     * <code>IOS = 1;</code>
     */
    public static final int IOS_VALUE = 1;
    /**
     * <code>ANDROID = 2;</code>
     */
    public static final int ANDROID_VALUE = 2;
    /**
     * <code>HARMONYOS = 3;</code>
     */
    public static final int HARMONYOS_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static OsType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static OsType forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN_OS;
        case 1: return IOS;
        case 2: return ANDROID;
        case 3: return HARMONYOS;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<OsType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        OsType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<OsType>() {
            public OsType findValueByNumber(int number) {
              return OsType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return top.opendsp.proto.enums.OpenDspEnums.getDescriptor().getEnumTypes().get(0);
    }

    private static final OsType[] VALUES = values();

    public static OsType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private OsType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:top.opendsp.proto.OsType)
  }

  /**
   * <pre>
   * 投放方式：匀速/加速
   * </pre>
   *
   * Protobuf enum {@code top.opendsp.proto.DeliveryMode}
   */
  public enum DeliveryMode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKNOWN_DELIVERY = 0;</code>
     */
    UNKNOWN_DELIVERY(0),
    /**
     * <code>SMOOTH_DELIVERY = 1;</code>
     */
    SMOOTH_DELIVERY(1),
    /**
     * <code>SPEED_DELIVERY = 2;</code>
     */
    SPEED_DELIVERY(2),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 30,
        /* patch= */ 2,
        /* suffix= */ "",
        DeliveryMode.class.getName());
    }
    /**
     * <code>UNKNOWN_DELIVERY = 0;</code>
     */
    public static final int UNKNOWN_DELIVERY_VALUE = 0;
    /**
     * <code>SMOOTH_DELIVERY = 1;</code>
     */
    public static final int SMOOTH_DELIVERY_VALUE = 1;
    /**
     * <code>SPEED_DELIVERY = 2;</code>
     */
    public static final int SPEED_DELIVERY_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static DeliveryMode valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static DeliveryMode forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN_DELIVERY;
        case 1: return SMOOTH_DELIVERY;
        case 2: return SPEED_DELIVERY;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<DeliveryMode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        DeliveryMode> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<DeliveryMode>() {
            public DeliveryMode findValueByNumber(int number) {
              return DeliveryMode.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return top.opendsp.proto.enums.OpenDspEnums.getDescriptor().getEnumTypes().get(1);
    }

    private static final DeliveryMode[] VALUES = values();

    public static DeliveryMode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private DeliveryMode(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:top.opendsp.proto.DeliveryMode)
  }

  /**
   * <pre>
   * 推广类型
   * </pre>
   *
   * Protobuf enum {@code top.opendsp.proto.PromotionType}
   */
  public enum PromotionType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKNOWN_PROMOTION = 0;</code>
     */
    UNKNOWN_PROMOTION(0),
    /**
     * <code>WEBSITE = 1;</code>
     */
    WEBSITE(1),
    /**
     * <code>ANDROID_APP = 2;</code>
     */
    ANDROID_APP(2),
    /**
     * <code>IOS_APP = 3;</code>
     */
    IOS_APP(3),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 30,
        /* patch= */ 2,
        /* suffix= */ "",
        PromotionType.class.getName());
    }
    /**
     * <code>UNKNOWN_PROMOTION = 0;</code>
     */
    public static final int UNKNOWN_PROMOTION_VALUE = 0;
    /**
     * <code>WEBSITE = 1;</code>
     */
    public static final int WEBSITE_VALUE = 1;
    /**
     * <code>ANDROID_APP = 2;</code>
     */
    public static final int ANDROID_APP_VALUE = 2;
    /**
     * <code>IOS_APP = 3;</code>
     */
    public static final int IOS_APP_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PromotionType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static PromotionType forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN_PROMOTION;
        case 1: return WEBSITE;
        case 2: return ANDROID_APP;
        case 3: return IOS_APP;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<PromotionType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        PromotionType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PromotionType>() {
            public PromotionType findValueByNumber(int number) {
              return PromotionType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return top.opendsp.proto.enums.OpenDspEnums.getDescriptor().getEnumTypes().get(2);
    }

    private static final PromotionType[] VALUES = values();

    public static PromotionType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private PromotionType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:top.opendsp.proto.PromotionType)
  }

  /**
   * <pre>
   * 出价方式
   * </pre>
   *
   * Protobuf enum {@code top.opendsp.proto.BiddingMethod}
   */
  public enum BiddingMethod
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKNOWN_BIDDING = 0;</code>
     */
    UNKNOWN_BIDDING(0),
    /**
     * <code>CPC = 1;</code>
     */
    CPC(1),
    /**
     * <code>CPM = 2;</code>
     */
    CPM(2),
    /**
     * <code>CPA = 3;</code>
     */
    CPA(3),
    /**
     * <code>OCPM = 4;</code>
     */
    OCPM(4),
    /**
     * <code>OCPC = 5;</code>
     */
    OCPC(5),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 30,
        /* patch= */ 2,
        /* suffix= */ "",
        BiddingMethod.class.getName());
    }
    /**
     * <code>UNKNOWN_BIDDING = 0;</code>
     */
    public static final int UNKNOWN_BIDDING_VALUE = 0;
    /**
     * <code>CPC = 1;</code>
     */
    public static final int CPC_VALUE = 1;
    /**
     * <code>CPM = 2;</code>
     */
    public static final int CPM_VALUE = 2;
    /**
     * <code>CPA = 3;</code>
     */
    public static final int CPA_VALUE = 3;
    /**
     * <code>OCPM = 4;</code>
     */
    public static final int OCPM_VALUE = 4;
    /**
     * <code>OCPC = 5;</code>
     */
    public static final int OCPC_VALUE = 5;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static BiddingMethod valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static BiddingMethod forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN_BIDDING;
        case 1: return CPC;
        case 2: return CPM;
        case 3: return CPA;
        case 4: return OCPM;
        case 5: return OCPC;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<BiddingMethod>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        BiddingMethod> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<BiddingMethod>() {
            public BiddingMethod findValueByNumber(int number) {
              return BiddingMethod.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return top.opendsp.proto.enums.OpenDspEnums.getDescriptor().getEnumTypes().get(3);
    }

    private static final BiddingMethod[] VALUES = values();

    public static BiddingMethod valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private BiddingMethod(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:top.opendsp.proto.BiddingMethod)
  }

  /**
   * Protobuf enum {@code top.opendsp.proto.DeviceType}
   */
  public enum DeviceType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKNOWN_DEVICE_TYPE = 0;</code>
     */
    UNKNOWN_DEVICE_TYPE(0),
    /**
     * <code>PHONE = 1;</code>
     */
    PHONE(1),
    /**
     * <code>TABLET = 2;</code>
     */
    TABLET(2),
    /**
     * <code>CONNECTED_TV = 3;</code>
     */
    CONNECTED_TV(3),
    /**
     * <code>PC = 4;</code>
     */
    PC(4),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 30,
        /* patch= */ 2,
        /* suffix= */ "",
        DeviceType.class.getName());
    }
    /**
     * <code>UNKNOWN_DEVICE_TYPE = 0;</code>
     */
    public static final int UNKNOWN_DEVICE_TYPE_VALUE = 0;
    /**
     * <code>PHONE = 1;</code>
     */
    public static final int PHONE_VALUE = 1;
    /**
     * <code>TABLET = 2;</code>
     */
    public static final int TABLET_VALUE = 2;
    /**
     * <code>CONNECTED_TV = 3;</code>
     */
    public static final int CONNECTED_TV_VALUE = 3;
    /**
     * <code>PC = 4;</code>
     */
    public static final int PC_VALUE = 4;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static DeviceType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static DeviceType forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN_DEVICE_TYPE;
        case 1: return PHONE;
        case 2: return TABLET;
        case 3: return CONNECTED_TV;
        case 4: return PC;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<DeviceType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        DeviceType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<DeviceType>() {
            public DeviceType findValueByNumber(int number) {
              return DeviceType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return top.opendsp.proto.enums.OpenDspEnums.getDescriptor().getEnumTypes().get(4);
    }

    private static final DeviceType[] VALUES = values();

    public static DeviceType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private DeviceType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:top.opendsp.proto.DeviceType)
  }

  /**
   * Protobuf enum {@code top.opendsp.proto.ConnectionType}
   */
  public enum ConnectionType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKNOWN_CONNECTION_TYPE = 0;</code>
     */
    UNKNOWN_CONNECTION_TYPE(0),
    /**
     * <code>ETHERNET = 1;</code>
     */
    ETHERNET(1),
    /**
     * <code>WIFI = 2;</code>
     */
    WIFI(2),
    /**
     * <code>CELL_2G = 3;</code>
     */
    CELL_2G(3),
    /**
     * <code>CELL_3G = 4;</code>
     */
    CELL_3G(4),
    /**
     * <code>CELL_4G = 5;</code>
     */
    CELL_4G(5),
    /**
     * <code>CELL_5G = 6;</code>
     */
    CELL_5G(6),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 30,
        /* patch= */ 2,
        /* suffix= */ "",
        ConnectionType.class.getName());
    }
    /**
     * <code>UNKNOWN_CONNECTION_TYPE = 0;</code>
     */
    public static final int UNKNOWN_CONNECTION_TYPE_VALUE = 0;
    /**
     * <code>ETHERNET = 1;</code>
     */
    public static final int ETHERNET_VALUE = 1;
    /**
     * <code>WIFI = 2;</code>
     */
    public static final int WIFI_VALUE = 2;
    /**
     * <code>CELL_2G = 3;</code>
     */
    public static final int CELL_2G_VALUE = 3;
    /**
     * <code>CELL_3G = 4;</code>
     */
    public static final int CELL_3G_VALUE = 4;
    /**
     * <code>CELL_4G = 5;</code>
     */
    public static final int CELL_4G_VALUE = 5;
    /**
     * <code>CELL_5G = 6;</code>
     */
    public static final int CELL_5G_VALUE = 6;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ConnectionType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ConnectionType forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN_CONNECTION_TYPE;
        case 1: return ETHERNET;
        case 2: return WIFI;
        case 3: return CELL_2G;
        case 4: return CELL_3G;
        case 5: return CELL_4G;
        case 6: return CELL_5G;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ConnectionType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ConnectionType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ConnectionType>() {
            public ConnectionType findValueByNumber(int number) {
              return ConnectionType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return top.opendsp.proto.enums.OpenDspEnums.getDescriptor().getEnumTypes().get(5);
    }

    private static final ConnectionType[] VALUES = values();

    public static ConnectionType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ConnectionType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:top.opendsp.proto.ConnectionType)
  }

  /**
   * Protobuf enum {@code top.opendsp.proto.Carrier}
   */
  public enum Carrier
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKNOWN_CARRIER = 0;</code>
     */
    UNKNOWN_CARRIER(0),
    /**
     * <pre>
     * 移动
     * </pre>
     *
     * <code>MOBILE = 1;</code>
     */
    MOBILE(1),
    /**
     * <pre>
     * 联通
     * </pre>
     *
     * <code>UNICOM = 2;</code>
     */
    UNICOM(2),
    /**
     * <pre>
     * 电信
     * </pre>
     *
     * <code>TELECOM = 3;</code>
     */
    TELECOM(3),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 30,
        /* patch= */ 2,
        /* suffix= */ "",
        Carrier.class.getName());
    }
    /**
     * <code>UNKNOWN_CARRIER = 0;</code>
     */
    public static final int UNKNOWN_CARRIER_VALUE = 0;
    /**
     * <pre>
     * 移动
     * </pre>
     *
     * <code>MOBILE = 1;</code>
     */
    public static final int MOBILE_VALUE = 1;
    /**
     * <pre>
     * 联通
     * </pre>
     *
     * <code>UNICOM = 2;</code>
     */
    public static final int UNICOM_VALUE = 2;
    /**
     * <pre>
     * 电信
     * </pre>
     *
     * <code>TELECOM = 3;</code>
     */
    public static final int TELECOM_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Carrier valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Carrier forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN_CARRIER;
        case 1: return MOBILE;
        case 2: return UNICOM;
        case 3: return TELECOM;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Carrier>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Carrier> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Carrier>() {
            public Carrier findValueByNumber(int number) {
              return Carrier.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return top.opendsp.proto.enums.OpenDspEnums.getDescriptor().getEnumTypes().get(6);
    }

    private static final Carrier[] VALUES = values();

    public static Carrier valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Carrier(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:top.opendsp.proto.Carrier)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013enums.proto\022\021top.opendsp.proto*=\n\006OsTy" +
      "pe\022\016\n\nUNKNOWN_OS\020\000\022\007\n\003IOS\020\001\022\013\n\007ANDROID\020\002" +
      "\022\r\n\tHARMONYOS\020\003*M\n\014DeliveryMode\022\024\n\020UNKNO" +
      "WN_DELIVERY\020\000\022\023\n\017SMOOTH_DELIVERY\020\001\022\022\n\016SP" +
      "EED_DELIVERY\020\002*Q\n\rPromotionType\022\025\n\021UNKNO" +
      "WN_PROMOTION\020\000\022\013\n\007WEBSITE\020\001\022\017\n\013ANDROID_A" +
      "PP\020\002\022\013\n\007IOS_APP\020\003*S\n\rBiddingMethod\022\023\n\017UN" +
      "KNOWN_BIDDING\020\000\022\007\n\003CPC\020\001\022\007\n\003CPM\020\002\022\007\n\003CPA" +
      "\020\003\022\010\n\004OCPM\020\004\022\010\n\004OCPC\020\005*V\n\nDeviceType\022\027\n\023" +
      "UNKNOWN_DEVICE_TYPE\020\000\022\t\n\005PHONE\020\001\022\n\n\006TABL" +
      "ET\020\002\022\020\n\014CONNECTED_TV\020\003\022\006\n\002PC\020\004*y\n\016Connec" +
      "tionType\022\033\n\027UNKNOWN_CONNECTION_TYPE\020\000\022\014\n" +
      "\010ETHERNET\020\001\022\010\n\004WIFI\020\002\022\013\n\007CELL_2G\020\003\022\013\n\007CE" +
      "LL_3G\020\004\022\013\n\007CELL_4G\020\005\022\013\n\007CELL_5G\020\006*C\n\007Car" +
      "rier\022\023\n\017UNKNOWN_CARRIER\020\000\022\n\n\006MOBILE\020\001\022\n\n" +
      "\006UNICOM\020\002\022\013\n\007TELECOM\020\003B)\n\027top.opendsp.pr" +
      "oto.enumsB\014OpenDspEnumsH\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
