// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: services.proto
// Protobuf Java Version: 4.30.2

package top.opendsp.proto.rtb.service;

public final class OpenDspRtbServices {
  private OpenDspRtbServices() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 30,
      /* patch= */ 2,
      /* suffix= */ "",
      OpenDspRtbServices.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016services.proto\022\021top.opendsp.proto\032\013enu" +
      "ms.proto\032\trtb.proto2X\n\016BiddingService\022F\n" +
      "\003bid\022\035.top.opendsp.proto.BidRequest\032\036.to" +
      "p.opendsp.proto.BidResponse\"\000B5\n\035top.ope" +
      "ndsp.proto.rtb.serviceB\022OpenDspRtbServic" +
      "esH\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          top.opendsp.proto.enums.OpenDspEnums.getDescriptor(),
          top.opendsp.proto.rtb.OpenDspRtb.getDescriptor(),
        });
    descriptor.resolveAllFeaturesImmutable();
    top.opendsp.proto.enums.OpenDspEnums.getDescriptor();
    top.opendsp.proto.rtb.OpenDspRtb.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
